[package]
name = "casbin-rbatis-adapter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.21.2", features = ["full"] }
casbin = { version = "2.0.9", default-features = false, features = ["runtime-async-std", "logging", "incremental"] }
serde = { version = "1.0.147", features = ["derive"] }
async-trait = "0.1.60"
# rbatis integration
rbs = "0.1.13"
rbatis = "4.0.43"
rbdc-mysql = "0.1.18"